In [6]:
# notebook.ipynb

import pandas as pd
from meteostat import Stations, Daily
from weather_analysis.data_analis.data_processing import WeatherDataProcessor, save_to_excel

# Настройки
start = pd.Timestamp('2023-01-01')
end = pd.Timestamp('2023-12-31')

# Получение данных о погоде
stations = Stations()
station = stations.nearby(55.7558, 37.6173).fetch(1)
station_id = station.index[0]

data = Daily(station_id, start, end)
data = data.fetch()

# Преобразование данных
data = data[['tavg']]
data.columns = ['temperature']
data.dropna(inplace=True)

# Анализ данных
processor = WeatherDataProcessor(data)
processed_data = processor.process_data()

# Сохранение результата в Excel
save_to_excel(processed_data, 'weather_analysis.xlsx')

# Выводим промежуточные результаты
processed_data.head()

RuntimeWarning: Degrees of freedom <= 0 for slice
RuntimeWarning: divide by zero encountered in divide
RuntimeWarning: invalid value encountered in multiply

,temperature,moving_average,differential,autocorrelation,maxima,minima
time,,,,,,
2023-01-01,3.2,NaN,NaN,1.000000,NaN,NaN
2023-01-02,0.5,NaN,-2.7,0.971500,NaN,NaN
2023-01-03,-0.4,NaN,-0.9,0.932665,NaN,NaN
2023-01-04,-2.1,NaN,-1.7,0.903932,NaN,NaN
2023-01-05,-6.1,NaN,-4.0,0.878426,NaN,NaN